### ISSUE TITLE
Página Web para usar en pc

### ISSUE THREAD

**Issue by LeaBertero** [isaias4912/full-stack-2022-lista-de-convocados#2]
Para que ?
Plataforma Web requerida y destinada para la carga de datos de jugadores de fútbol, para el Mundial Qatar 2023. (Equipo 26 jugadores).
La la misma debe contener:
- Carga de cada uno de la integrantes del equipo
- Listarlos una vez realizada dicha carga
- Poder realizar modificaciones en los datos ingresados por el usuario.
- poder eliminar un jugador de la lista y ser reemplazado por otro.
- Diseño(a realizarse)

**Comment by flavia-Arroyo** [comment]
Criterios de aceptación:
probar agregar mas de 26 jugadores(falla)
probar borrar el jugador n°11 de la lista (falla) 
probar agregar un nombre de jugador con números o más de 40 caracteres (falla)
probar reemplazar a un jugador sin incorporar todos los datos requeridos (falla)
