### ISSUE TITLE
Registro para los usuarios

### ISSUE THREAD

**Issue by LeaBertero** [isaias4912/full-stack-2022-lista-de-convocados#4]
Cuándo el usuario se registre, se van a necesitar los siguientes datos:
Nmbre y apellido:
Edad:
email:
Nombre de usuario:
contraseña:

un boton para validar todos los datos.

**Comment by flavia-Arroyo** [comment]
criterios de aceptación:
nombre y apellido se agregue numero o mas de 40 caracteres.... (falla)
edad... solo números, mayor o igual a  18 (pasa)
ciudad no existente en el pais elegido...(falla)
nombre de usuario... respete el formato determinado(pasa)
contraseña...respete el formato(pasa)

**Comment by AyelenCarronOK** [comment]
como usuario quiero que contraseña incorrecta falla
como usuario quiero recuperar contraseña via mail
